from __future__ import annotations

from enum import StrEnum


class LeadV12Status(StrEnum):
    DRAFT = "DRAFT"
    PUBLIC_POOL = "PUBLIC_POOL"
    PENDING_REVIEW = "PENDING_REVIEW"
    PENDING_TELESALES_VERIFY = "PENDING_TELESALES_VERIFY"
    PENDING_OPERATION_DISPOSITION = "PENDING_OPERATION_DISPOSITION"
    READY_DISPATCH = "READY_DISPATCH"
    DISPATCHED = "DISPATCHED"
    CLAIMED = "CLAIMED"
    FOLLOWING = "FOLLOWING"
    COMPLETED = "COMPLETED"
    INVALID = "INVALID"
    DUPLICATE = "DUPLICATE"
    CLOSED = "CLOSED"


class LeadSourceKind(StrEnum):
    PLATFORM_MANUAL = "PLATFORM_MANUAL"
    SUPPLIER_H5 = "SUPPLIER_H5"
    FEISHU_IMPORT = "FEISHU_IMPORT"
    FEISHU_LEGACY = "FEISHU_LEGACY"


class CustomerSource(StrEnum):
    OPERATION_ENTRY = "OPERATION_ENTRY"
    FRANCHISE_SUPPLIED = "FRANCHISE_SUPPLIED"


class LeadReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DuplicateDecision(StrEnum):
    CLEAR = "CLEAR"
    HARD_DUPLICATE = "HARD_DUPLICATE"
    REWARD_DUPLICATE = "REWARD_DUPLICATE"
    HISTORICAL_SUSPECT = "HISTORICAL_SUSPECT"
    OVERRIDDEN = "OVERRIDDEN"


class ReturnV12Status(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    VERIFYING = "VERIFYING"
    REVIEWING = "REVIEWING"
    NEED_MORE_EVIDENCE = "NEED_MORE_EVIDENCE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ReturnReasonCode(StrEnum):
    EMPTY_NUMBER = "EMPTY_NUMBER"
    OUT_OF_SERVICE_REGION = "OUT_OF_SERVICE_REGION"
    DUPLICATE_TO_RECEIVER = "DUPLICATE_TO_RECEIVER"
    NON_HOUSING_CONSULTATION = "NON_HOUSING_CONSULTATION"


class VerificationTaskType(StrEnum):
    PRE_DISPATCH_VERIFY = "PRE_DISPATCH_VERIFY"
    RETURN_VERIFY = "RETURN_VERIFY"
    LEAD_VERIFY_LEGACY = "LEAD_VERIFY_LEGACY"


class RewardStatus(StrEnum):
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
    WAITING_CLAIM = "WAITING_CLAIM"
    OBSERVING = "OBSERVING"
    FROZEN = "FROZEN"
    SETTLED = "SETTLED"
    CANCELLED = "CANCELLED"
    REVERSED = "REVERSED"


class CompanyLeadCapabilityCode(StrEnum):
    LEAD_SUPPLIER = "LEAD_SUPPLIER"
    LEAD_RECEIVER = "LEAD_RECEIVER"


class ReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    NEED_MORE = "NEED_MORE"
